import { html } from 'lit-html';
import * as litHtmlPrivate_1 from "lit-html/private-ssr-support.js";
const { AttributePart: A_1 } = litHtmlPrivate_1._$LH;
const b_1 = i => i;
const lit_template_1 = { h: b_1 `<div></div>`, parts: [{ type: 1, index: 0, name: "data-attr", strings: ["", ""], ctor: A_1 }] };
const attributePart = { ["_$litType$"]: lit_template_1, values: ['attributeValue'] };
const lit_template_2 = { h: b_1 `<div></div>`, parts: [{ type: 1, index: 0, name: "data-attr", strings: ["static ", " middle ", " end"], ctor: A_1 }] };
const multipleAttributeParts = { ["_$litType$"]: lit_template_2, values: ['value-one', 'value-two'] };
const lit_template_3 = { h: b_1 `<div></div>`, parts: [{ type: 1, index: 0, name: "data-attr", strings: ["", ""], ctor: A_1 }] };
const noQuotes = { ["_$litType$"]: lit_template_3, values: ['no-quotes-value'] };
