/**
 * @license
 * Copyright 2022 Google LLC
 * SPDX-License-Identifier: BSD-3-Clause
 */

import {javascript} from '@lit-labs/gen-utils/lib/str-utils.js';

// Not only need to rename files in the root directory,
// but files in subPath also need to be renamed.
export const renameTemplate = () =>
  javascript`import fs from 'fs';
import path from 'path';
import {fileURLToPath} from 'url';

/** This script renames type declaration files generated by \`vue-tsc\` from
 * e.g. \`ElementName.vue.d.ts\` to \`ElementName.d.ts\` so that they match
 * generated component names of e.g. \`ElementName.ts\`.
 */
const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const root = \`\${__dirname}/..\`;

function traverseRename(directoryPath) {
  const files = fs.readdirSync(directoryPath);

  for (const file of files) {
    const filePath = path.join(directoryPath, file);
    const stat = fs.statSync(filePath);
    if (stat.isFile()) {
      if (file.endsWith('.vue.d.ts')) {
        fs.renameSync(
          filePath,
          \`\${filePath.replace('.vue.d.ts', '.d.ts')}\`,
          (err) => {
            console.log(err);
          }
        );
      }
    } else if (stat.isDirectory()) {
      traverseRename(filePath); // 递归遍历子目录
    }
  }
}

traverseRename(root);
`;
